name: CI — build Docker images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend-drf
          file: ./backend-drf/Dockerfile
          push: false
          tags: backend:test
      - name: Run backend tests
        run: docker run --rm backend:test python manage.py test
      - name: Build frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-react/frontUi
          file: ./frontend-react/frontUi/Dockerfile
          push: false
          tags: frontend:test
